### ISSUE TITLE
[FeatureReq - Edge Addons site] <black theme>

### ISSUE THREAD

**Issue by DennyKhansan** [microsoft/MicrosoftEdge-Extensions#105]
**Is your feature request related to a problem? Please describe.**
I wish there was fourth option to the theme mode under appearance in settings.

**Describe the solution you'd like**
A super black theme not dark theme mode added.

**Describe alternatives you've considered**
.

**Additional context**
It would be nice if can choose custom accent colors.

**Comment by Bhuvana-Priya** [comment]
Thank you for the request @DennyKhansan , I will pass this on to the right team and update you accordingly

**Comment by ManikanthMSFT** [comment]
Hi @DennyKhansan Please be informed that we have forwarded your feedback to our team for further consideration, inclusion the darker theme option.

Also, if you have any issues regarding Addons, please contact us at [ext_dev_support@microsoft.com](mailto:ext_dev_support@microsoft.com) so that we can assist you accordingly.
