### ISSUE TITLE
[FeatureReq - Edge Addons site] Swap in a new extension update before review process

### ISSUE THREAD

**Issue by joelataccelm** [microsoft/MicrosoftEdge-Extensions#106]
The problem that I'm having with Edge is that it takes 10 days before my extension is published.
In that time I might release several additional updates for safari, firefox, and chrome during our busy season.
To make it easier to get critical extension bugs fixed as soon as possible, please allow us to replace the previously uploaded update, without resetting the review process clock. I don't know if it currently works this way, as I'm too afraid to attempt it.

I imagine the review itself is relatively quick, it's just the wait for an available reviewer is what causes this to be so painfully slow? If that's the case there should be no harm in swapping out the update with a new version, but still keep your place in line.

**Comment by Bhuvana-Priya** [comment]
Hi @joelataccelm,

The review times for Edge extension submissions has improved in the recent times. Please provide us more details of your extension and the submission you are referring to @ext_dev_support@microsoft.com

**Comment by joelataccelm** [comment]
I'm currently on day 9. I've never seen it approved faster than 10 days.. I have critical updates that need to go live.
You’ve somehow managed to survive the browser wars by slapping your logo on Chrome – but now is the time to make things right with developers and Edge users. Please get these approved faster.

**Comment by ManikanthMSFT** [comment]
Hi @joelataccelm, we apologize for this inconvenience.

Please be informed that we have forwarded your feedback to our team for further consideration, resulting in a shorter review and extension review cycle time.

Also, if you have any issues while submiting your extensions, please contact us at [ext_dev_support@microsoft.com](mailto:ext_dev_support@microsoft.com) so that we can assist you accordingly.
