### ISSUE TITLE
[FeatureReq - Partner Center] Fast track extension review cycle

### ISSUE THREAD

**Issue by yogesh-morankar** [microsoft/MicrosoftEdge-Extensions#131]
Respected,

Current release cycle includes 7 business days for extension review by Microsoft.
This time is too much for Enterprise extensions. Also this time is way too much as compared to Firefox and Chrome.
This delays our urgent hotfixes on the production environment and results in business impact.

If you can optimize the release cycle aligned with other browsers release cycle, it will be a great improvement to the enterprise extension.

**Comment by Jaifroid** [comment]
Totally agree with this. I have an extension (Kiwix JS) I publish on Mozilla, Chrome and Edge extension stores. These are the normal timeframes for each:

* Mozilla - published **instantly** after automated review (subject to potential human review later)
* Chrome - 24 hours
* Edge - up to 9 days (sorry, but the trick of counting only "business" days doesn't wash here, given that Chrome extension gets reviewed at weekends just fine)

Does Microsoft actually want to promote its Edge extension store and use of its browser? At this point, what incentive do I have for not just telling my users to go and install it from the Chrome store if they use Edge? And while they're at it, probably half of them will switch to Chrome anyway.

**Comment by Jaifroid** [comment]
See also the discussion here: https://github.com/microsoft/MicrosoftEdge-Extensions/discussions/46

**Comment by prithamkasiMSFT** [comment]
@Jaifroid @yogesh-morankar 
Hi, we understand that there have been delays in the approval timelines. Could you please reach out to us at ext_dev_support@microsoft.com with your submission details and we will look into it.

**Comment by Jaifroid** [comment]
@prithamkasiMSFT I don't currently have a release under approval. But what we are signalling is a systemic issue. It can't be fixed by asking specific contributors to contact you when they submit. That's at best a sticking plaster for specific cases.

**Comment by infinitepower18** [comment]
It seems there has been no effort at all when it comes to improving the review time. Users who install my extension from the Edge store will have to wait a few days for an update that is already available in the other stores. Why should they use your store then, when they can get quicker updates via the Chrome Web Store?

**Comment by prithamkasiMSFT** [comment]
Hello Ahnaf,

Thank you for reaching out to us!

Could you please share the details of your extension and we could investigate and get back to you as soon as we can?

Best regards,
Pritham Kasi
Community Manager - Microsoft Edge Add-ons

For any specific questions related to Partner Center and Edge add-ons store, please report them via our GitHub developer community<https://github.com/microsoft/MicrosoftEdge-Extensions>.

**Comment by Jaifroid** [comment]
@prithamkasiMSFT You need to stop asking people for their extension details. We don't want individual sticking plasters. We want a system change, so that ALL extensions get reviewed swiftly. It should be 24 hours for uncomplicated cases, and 72 hours when manual review is required. All you need is a concerted effort to get on top of the queue now, and then ensure you stay on top of reviews. If you're chronically under-staffed, you need to tell MSFT, which is a multi-billion-dollar company.

**Comment by Manikanth2109** [comment]
Hello @Jaifroid @infinitepower18 @yogesh-morankar, we apologize for this inconvenience. 

Please be informed that we have forwarded your feedback to our team for further consideration, resulting in a shorter review and extension review cycle time.

Also, if you have any issues while submitting your extensions, please contact us at ext_dev_support@microsoft.com so that we can investigate and assist you accordingly.

**Comment by Manikanth2109** [comment]
Hello @Jaifroid @infinitepower18 @yogesh-morankar, we apologize for this inconvenience. 

Please be informed that we have forwarded your feedback to our team for further consideration, resulting in a shorter review and extension review cycle time.

Also, if you have any issues while submiting your extensions, please contact us at ext_dev_support@microsoft.com so that we can investigate and assist you accordingly.

**Comment by Jaifroid** [comment]
OK, thank you.

**Comment by yogesh-morankar** [comment]
Thank you  @Manikanth2109  for understanding and raising this issue with concerning team.
