### ISSUE TITLE
扩展程序审核失败问题 Extension program review failure issue

### ISSUE THREAD

**Issue by X-X-X-X-X-X-X-X-X-X-X-X-X** [microsoft/MicrosoftEdge-Extensions#177]
我提交了一个恢复关闭页面的扩展程序，但审核失败提示该扩展程序没有提供价值，可是点击图标即恢复关闭页面功能对一部分人来讲十分有用，我观察到也有类似的程序已经上架到了扩展商店，但他们的实现并不理想，所以审核失败就因为我只是调用了官方api吗？所以官方会在edge浏览器上添加一项点击就恢复关闭页面的图标吗？

I submitted an extension to restore the closed page, but the review failed and prompted that Your extension does not offer lasting value. However, the function of restoring the closed page by clicking on the icon is very useful for some people. I have observed that similar programs have also been listed in the extension store, but their implementation is not ideal. So, the review failed because I only called the official API? So will the official add an icon on the Edge browser to restore the closed page upon clicking?And I can successfully list the program on the Chrome extension store.

Product ID: 3d130dba-7a7b-4388-9101-1ce7a5a125a4

**Comment by ManikanthMSFT** [comment]
Hey there, thank you for contacting us. We are currently looking into your concern and will update you as soon as we have more information.

**Comment by X-X-X-X-X-X-X-X-X-X-X-X-X** [comment]
thanks

**Comment by ManikanthMSFT** [comment]
Hey @X-X-X-X-X-X-X-X-X-X-X-X-X, thank you for your patience and for providing detailed information about your extension.

We understand that the functionality of restoring a closed page by clicking on the icon can be useful for many users. However, our review process determined that your extension does not offer lasting value as it mimics existing browser features, which is why it was not approved.

While similar programs may exist in the extension store, our guidelines require that new extensions provide unique and lasting value beyond what is already available in the browser. The use of the official API alone does not meet this criterion.

The product was failed for [1.1.3](https://learn.microsoft.com/en-us/legal/microsoft-edge/extensions/developer-policies#113-functionality) Functionality – Lasting value with the fail note “Your extension does not offer lasting value. Your product mimics existing features in the browser.”

We recommend you to please make the necessary changes and resubmit your subscription.
