### ISSUE TITLE
[Bug - Partner Center] Issues with Partner Center - Loading Content

### ISSUE THREAD

**Issue by nagachaitanyalokam** [microsoft/MicrosoftEdge-Extensions#32]
**Describe the bug**
Content on Microsoft Partner Center is not loading across browsers, Unable to publish browser Extension to Edge Add-ons Store.

**To Reproduce**
1. Go to '[Partner Center](https://partner.microsoft.com/dashboard/microsoftedge/public/login?ref=dd)'
2. Select 'Account settings' and click on 'My access'. 
3. Error displayed: "There was a problem in fetching data. Please reload the page or try again later."

**Expected behavior**
Details of my access should be available for extension developer to refer.

**Screenshots**
![image](https://user-images.githubusercontent.com/6248594/173754749-55f31ae2-ec5a-4e55-af24-4fcc884e66aa.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge, Chrome, safari

**Additional context**
User Tweet Link: https://twitter.com/LizzyReborn/status/1536864262169034754

**Comment by LizAinslie** [comment]
As the original author of this tweet, I'd like to mention the scope of this issue is far beyond just "loading content". I'm having errors all over the site with content flashing then just disappearing and not being able to submit forms, among multitudes of other small issues. The site also performs terribly overall and as much as I dislike Microsoft I still expect far better than this.

**Comment by nagachaitanyalokam** [comment]
Noted. Thanks for letting us know about the issues. I've shared the details with our engineers.

**Comment by nagachaitanyalokam** [comment]
Hello @LizAinslie, our Engineering team confirmed that the issue is now resolved. Please check and let us know if you're still facing the same problem or anything else that we could help you. Thanks!
