### ISSUE TITLE
msedge.exe processes stay running after browser is closed

### ISSUE THREAD

**Issue by oreznichenko-mwb** [microsoft/MicrosoftEdge-Extensions#51]
**Describe the bug**
When MS Edge browser is closed, processes on background stay active and msedge.exe has <Non-existent Process>(16984) as parent process

**To Reproduce**
1. Open MS edge browser
2. Navigate to the browser settings
3. Close MS edge browser
4. Open process explorer and find msedge.exe process in the list
**Expected behavior**
All msedge.exe processes are closed after closing browser

**Screenshots**
![MS edge process without parent process](https://user-images.githubusercontent.com/112410742/190981851-b94f12a6-81e5-454e-990a-c824ef11bcd2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 21H2
 - Browser: Microsoft Edge
 - Version: 105.0.1343.42 (Official build) (64-bit)

![MS edge with non-existent parent process](https://user-images.githubusercontent.com/112410742/190983973-541e31c9-c582-4ef7-ba74-08d1c77fdbf3.gif)

**Comment by nagachaitanyalokam** [comment]
Hello, 

We are currently checking about the issue reported with our engineering team. Will keep you posted. 

Thanks!

**Comment by MaheshKumarJha** [comment]
@oreznichenko-mwb Can you share the full command line of the process that stays active in the background?

**Comment by oreznichenko-mwb** [comment]
**When browser is opened:** "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --profile-directory=Default
**When browser is closed:** "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --no-startup-window /prefetch:5 
![2022-09-21 08_39_18-msedge exe processes stay running after browser is closed · Issue #51 · microsof](https://user-images.githubusercontent.com/112410742/191423179-3824648f-315e-41d4-9eec-62fd0baef952.png)

**Comment by sivsouvamMSFT** [comment]
Hi @oreznichenko-mwb, thank you for reaching out to us. We figured out the issue is not related to the Microsoft Edge Add-ons. It is suggested to report via Send Feedback option to get connected with the correct team regarding this issue. 

**To Send Feedback:**

1. In the new Microsoft Edge, press Alt+Shift+I. The Send Feedback window opens. The focus is in the feedback text field.

2. Type your feedback.

3. Your account email address is included in the feedback by default. If you want to send your comments without your email address, press Tab until you hear “Include email address checkbox checked,” and press the spacebar.

4. If you don’t want to send diagnostics data with your feedback, press Tab until you hear “Send diagnostic data, checkbox checked,” and press the spacebar.

5. To send your feedback, press Tab until you reach the Send button, and press Enter.
