### ISSUE TITLE
[Bug - Edge Addons] Microsoft Editor plugin is messing our website and I can't find contact info

### ISSUE THREAD

**Issue by izikl** [microsoft/MicrosoftEdge-Extensions#80]
**Describe the bug**
This plugin https://microsoftedge.microsoft.com/addons/detail/microsoft-editor-spellin/hokifickgkhplphjiodbggjmoafhignh messes up https://dataexplorer.azure.com. How can I find the team that owns that plugin and ask for help?  

**To Reproduce**
1. Install plugin [Microsoft Editor](https://microsoftedge.microsoft.com/addons/detail/microsoft-editor-spellin/hokifickgkhplphjiodbggjmoafhignh)
2. Go to https://dataexplorer.azure.com 
3. The most obvious issue is that the entire left nav is not showing 
4. The [plugin page](https://microsoftedge.microsoft.com/addons/detail/microsoft-editor-spellin/hokifickgkhplphjiodbggjmoafhignh) doesn't show any indication on how to contact the team that developed this plugin.

**Expected behavior**
Have a better way to find the owner of Microsoft Editor, or if this team owns Microsoft Editor please contact me to talk about the bug in Azure Data Explorer

**Screenshots**
No Contact Info:
![image](https://user-images.githubusercontent.com/8294298/225710555-4406ca83-4e49-4f98-97a7-0767ec831ff2.png)

Same on the installed extension page:
![image](https://user-images.githubusercontent.com/8294298/225710921-2d465473-bd71-4551-a039-c2b6518c378e.png)

Editor extension is enabled and causes left navigation to now showing:
![image](https://user-images.githubusercontent.com/8294298/225711315-73d692fd-3edf-482f-85ef-a86d1a02e400.png)

**Desktop (please complete the following information):**
 - OS: Mac/Windows
 - Browser Edge
 - Version - all

**Comment by sivsouvamMSFT** [comment]
Hi @izikl, thanks for reaching out to us.

Upon reviewing your recent activity, we noticed that you had previously opened a bug and subsequently closed it. We hope that this means your issue was successfully resolved, and that you are now able to use the product without any further issues.

If you do require any further assistance, please do not hesitate to reach out to us here. We are available to help you with any questions or concerns you may have, and we are committed to providing you with the best possible support.
